version: '3'
volumes:
  vendor_bundle:
  vendor_assets:
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres 
 
  aniboard:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/aniboard
      - vendor_bundle:/aniboard-portfolio/vendor/bundle
      - vendor_assets:/aniboard-portfolio/vendor/assets
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - chrome
    stdin_open: true
    tty: true
    environment:
      - 'POSTGRES_PASSWORD=postgres' 
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444