version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
  ruby: circleci/ruby@1.1.4
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

executors:
  default:
    working_directory: ~/aniboard
    docker:
      - image: cimg/ruby:2.6.6-browsers
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: app_user
          POSTGRES_DB: Aniboard_portfolio_test
          POSTGRES_PASSWORD: "postgres"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: app_user
      PGPASSWORD: "postgres"
      RAILS_ENV: test

commands:
  setup:
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn add bootstrap@next
      - run: sudo apt-get update
      - run: sudo apt-get -y install imagemagick
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version

jobs:
  rspec:
    executor: default
    steps:
      - setup
      - ruby/install-deps
      - run: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - run: sudo apt-get install -y fonts-noto-cjk
      - store_artifacts:
          path: tmp/screenshots
          destination: test-screenshots

  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  heroku_deploy:
    executor: default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build:
    jobs:
      - rspec
      - rubocop
      - heroku_deploy:
          requires:
            - rspec
            - rubocop

